# SETUP

In [1]:
import pandas as pd
from matplotlib import rcParams
from datetime import timedelta  

%matplotlib inline
rcParams['font.family'] = 'DejaVu Sans'

In [1]:
# 2016
file_2016_temperature_3H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_temperature_3H.csv'
file_2016_temperature_max = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_temperature_max.csv'
file_2016_temperature_min = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_temperature_min.csv'
file_2016_sky = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_sky.csv'
file_2016_precipitation_form = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_precipitation_form.csv'
file_2016_rainfall_probability = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_rainfall_probability.csv'
file_2016_rainfall_6H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_rainfall_6H.csv'
file_2016_snow_6H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_snow_6H.csv'
file_2016_humidity = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_humidity.csv'
file_2016_wind_speed = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_wind_speed.csv'
file_2016_wind_direction = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2016_wind_direction.csv'

# 2017
file_2017_temperature_3H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_temperature_3H.csv'
file_2017_temperature_max = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_temperature_max.csv'
file_2017_temperature_min = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_temperature_min.csv'
file_2017_sky = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_sky.csv'
file_2017_precipitation_form = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_precipitation_form.csv'
file_2017_rainfall_probability = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_rainfall_probability.csv'
file_2017_rainfall_6H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_rainfall_6H.csv'
file_2017_snow_6H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_snow_6H.csv'
file_2017_humidity = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_humidity.csv'
file_2017_wind_speed = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_wind_speed.csv'
file_2017_wind_direction = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2017_wind_direction.csv'

# 2018
file_2018_temperature_3H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_temperature_3H.csv'
file_2018_temperature_max = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_temperature_max.csv'
file_2018_temperature_min = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_temperature_min.csv'
file_2018_sky = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_sky.csv'
file_2018_precipitation_form = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_precipitation_form.csv'
file_2018_rainfall_probability = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_rainfall_probability.csv'
file_2018_rainfall_6H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_rainfall_6H.csv'
file_2018_snow_6H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_snow_6H.csv'
file_2018_humidity = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_humidity.csv'
file_2018_wind_speed = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_wind_speed.csv'
file_2018_wind_direction = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2018_wind_direction.csv'

# 2019
file_2019_temperature_3H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_temperature_3H.csv'
file_2019_temperature_max = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_temperature_max.csv'
file_2019_temperature_min = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_temperature_min.csv'
file_2019_sky = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_sky.csv'
file_2019_precipitation_form = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_precipitation_form.csv'
file_2019_rainfall_probability = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_rainfall_probability.csv'
file_2019_rainfall_6H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_rainfall_6H.csv'
file_2019_snow_6H = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_snow_6H.csv'
file_2019_humidity = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_humidity.csv'
file_2019_wind_speed = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_wind_speed.csv'
file_2019_wind_direction = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/2019_wind_direction.csv'

In [2]:
# 2016
data_2016_temperature_3H = pd.read_csv(file_2016_temperature_3H)
data_2016_temperature_max = pd.read_csv(file_2016_temperature_max)
data_2016_temperature_min = pd.read_csv(file_2016_temperature_min)
data_2016_sky = pd.read_csv(file_2016_sky)
data_2016_precipitation_form = pd.read_csv(file_2016_precipitation_form)
data_2016_rainfall_probability = pd.read_csv(file_2016_rainfall_probability)
data_2016_rainfall_6H = pd.read_csv(file_2016_rainfall_6H)
data_2016_snow_6H = pd.read_csv(file_2016_snow_6H)
data_2016_humidity = pd.read_csv(file_2016_humidity)
data_2016_wind_speed = pd.read_csv(file_2016_wind_speed)
data_2016_wind_direction = pd.read_csv(file_2016_wind_direction)

# 2017
data_2017_temperature_3H = pd.read_csv(file_2017_temperature_3H)
data_2017_temperature_max = pd.read_csv(file_2017_temperature_max)
data_2017_temperature_min = pd.read_csv(file_2017_temperature_min)
data_2017_sky = pd.read_csv(file_2017_sky)
data_2017_precipitation_form = pd.read_csv(file_2017_precipitation_form)
data_2017_rainfall_probability = pd.read_csv(file_2017_rainfall_probability)
data_2017_rainfall_6H = pd.read_csv(file_2017_rainfall_6H)
data_2017_snow_6H = pd.read_csv(file_2017_snow_6H)
data_2017_humidity = pd.read_csv(file_2017_humidity)
data_2017_wind_speed = pd.read_csv(file_2017_wind_speed)
data_2017_wind_direction = pd.read_csv(file_2017_wind_direction)

# 2018
data_2018_temperature_3H = pd.read_csv(file_2018_temperature_3H)
data_2018_temperature_max = pd.read_csv(file_2018_temperature_max)
data_2018_temperature_min = pd.read_csv(file_2018_temperature_min)
data_2018_sky = pd.read_csv(file_2018_sky)
data_2018_precipitation_form = pd.read_csv(file_2018_precipitation_form)
data_2018_rainfall_probability = pd.read_csv(file_2018_rainfall_probability)
data_2018_rainfall_6H = pd.read_csv(file_2018_rainfall_6H)
data_2018_snow_6H = pd.read_csv(file_2018_snow_6H)
data_2018_humidity = pd.read_csv(file_2018_humidity)
data_2018_wind_speed = pd.read_csv(file_2018_wind_speed)
data_2018_wind_direction = pd.read_csv(file_2018_wind_direction)

# 2018
data_2019_temperature_3H = pd.read_csv(file_2019_temperature_3H)
data_2019_temperature_max = pd.read_csv(file_2019_temperature_max)
data_2019_temperature_min = pd.read_csv(file_2019_temperature_min)
data_2019_sky = pd.read_csv(file_2019_sky)
data_2019_precipitation_form = pd.read_csv(file_2019_precipitation_form)
data_2019_rainfall_probability = pd.read_csv(file_2019_rainfall_probability)
data_2019_rainfall_6H = pd.read_csv(file_2019_rainfall_6H)
data_2019_snow_6H = pd.read_csv(file_2019_snow_6H)
data_2019_humidity = pd.read_csv(file_2019_humidity)
data_2019_wind_speed = pd.read_csv(file_2019_wind_speed)
data_2019_wind_direction = pd.read_csv(file_2019_wind_direction)

In [3]:
# 2016
print("2016")
print(data_2016_temperature_3H.shape)
print(data_2016_temperature_max.shape)
print(data_2016_temperature_min.shape)
print(data_2016_sky.shape)
print(data_2016_precipitation_form.shape)
print(data_2016_rainfall_probability.shape)
print(data_2016_rainfall_6H.shape)
print(data_2016_snow_6H.shape)
print(data_2016_humidity.shape)
print(data_2016_wind_speed.shape)
print(data_2016_wind_direction.shape, "\n")

# 2017
print("2017")
print(data_2017_temperature_3H.shape)
print(data_2017_temperature_max.shape)
print(data_2017_temperature_min.shape)
print(data_2017_sky.shape)
print(data_2017_precipitation_form.shape)
print(data_2017_rainfall_probability.shape)
print(data_2017_rainfall_6H.shape)
print(data_2017_snow_6H.shape)
print(data_2017_humidity.shape)
print(data_2017_wind_speed.shape)
print(data_2017_wind_direction.shape, "\n")

# 2018
print("2018")
print(data_2018_temperature_3H.shape)
print(data_2018_temperature_max.shape)
print(data_2018_temperature_min.shape)
print(data_2018_sky.shape)
print(data_2018_precipitation_form.shape)
print(data_2018_rainfall_probability.shape)
print(data_2018_rainfall_6H.shape)
print(data_2018_snow_6H.shape)
print(data_2018_humidity.shape)
print(data_2018_wind_speed.shape)
print(data_2018_wind_direction.shape, "\n")

# 2019
print("2019")
print(data_2019_temperature_3H.shape)
print(data_2019_temperature_max.shape)
print(data_2019_temperature_min.shape)
print(data_2019_sky.shape)
print(data_2019_precipitation_form.shape)
print(data_2019_rainfall_probability.shape)
print(data_2019_rainfall_6H.shape)
print(data_2019_snow_6H.shape)
print(data_2019_humidity.shape)
print(data_2019_wind_speed.shape)
print(data_2019_wind_direction.shape, "\n")

2016
(13618, 4)
(1750, 4)
(1474, 4)
(13618, 4)
(13618, 4)
(13618, 4)
(6994, 4)
(6994, 4)
(13618, 4)
(13618, 4)
(13618, 4)

2017
(54031, 4)
(6946, 4)
(5851, 4)
(54031, 4)
(50795, 4)
(54031, 4)
(27751, 4)
(27751, 4)
(54031, 4)
(54031, 4)
(54031, 4)

2018
(54031, 4)
(6946, 4)
(5851, 4)
(54031, 4)
(54031, 4)
(54031, 4)
(27751, 4)
(27751, 4)
(54031, 4)
(54031, 4)
(54031, 4)

2019
(8733, 4)
(1122, 4)
(945, 4)
(8733, 4)
(8733, 4)
(8733, 4)
(4485, 4)
(4485, 4)
(8733, 4)
(8733, 4)
(8733, 4)

# 노트
- 2, 3, 7, 8을 제외해야.
- temperature_3H, sky, precipitation_form, rainfall_probability, humidity, wind_speed, wind_direction
- 2017년 데이터셋 오류. sky, precipitation_form

---

### 데이터 통합 (변수 별)

In [8]:
def make_dataset(year=2018):
    
    if year == 2019:
        data_selected = [data_2019_temperature_3H, data_2019_sky, 
                         data_2019_rainfall_probability, data_2019_rainfall_6H, data_2019_snow_6H, 
                         data_2019_humidity, data_2019_wind_speed, data_2019_wind_direction]
    elif year == 2018:
        data_selected = [data_2018_temperature_3H, data_2018_sky, 
                         data_2018_rainfall_probability, data_2018_rainfall_6H, data_2018_snow_6H, 
                         data_2018_humidity, data_2018_wind_speed, data_2018_wind_direction]
    elif year == 2017:
        data_selected = [data_2017_temperature_3H, data_2017_sky, 
                         data_2017_rainfall_probability, data_2017_rainfall_6H, data_2017_snow_6H, 
                         data_2017_humidity, data_2017_wind_speed, data_2017_wind_direction]
    elif year == 2016:
        data_selected = [data_2016_temperature_3H, data_2016_sky, 
                         data_2016_rainfall_probability, data_2016_rainfall_6H, data_2016_snow_6H, 
                         data_2016_humidity, data_2016_wind_speed, data_2016_wind_direction]
    else:
        print("No selected year.")
    
    data_concat = pd.concat(data_selected, axis=1)

    # make day_, hour_, forecast_ and drop ...
    data_concat['day_'] = data_concat.iloc[:, :1].values
    data_concat['hour_'] = data_concat.iloc[:, 1:2].values
    data_concat['forecast_'] = data_concat.iloc[:, 2:3].values
    data_concat.drop([' format: day', 'hour', 'forecast'], axis=1, inplace=True)

    # change columns
    data_concat.columns = ['temperature_3H', 'sky', 'rainfall_probability', 'rainfall', 'snow', 'humidity', 
                           'wind_speed', 'wind_direction', 'day', 'hour', 'forecast']

    # fillna
    data_concat[['rainfall', 'snow']] = data_concat[['rainfall', 'snow']].fillna(0)

    # drop Nan Value
    data_concat = data_concat.dropna()
    
    return data_concat

### 8AM 선택, 날짜변경 (예보시기 -> 실제 시기)

In [9]:
year_name = [2016, 2017, 2018, 2019]

In [10]:
for year in year_name:

    # choose hour 8
    data_concat = make_dataset(year=year)
    data_concat = data_concat[data_concat.hour == 800.0]
    data_concat = data_concat[data_concat.forecast <= 25]
    print(data_concat.shape)

    # copy data_concat
    m = data_concat.shape[0]

    # reset index
    data_concat.reset_index(drop=True, inplace=True)

    # 실제 시기
    n = 4
    if year == 2016:
        data_concat.insert(loc=0, column='time', value=pd.date_range('{}-10-01'.format(str(year)), periods=m + n, freq='3H')[n:]) 
    else:
        data_concat.insert(loc=0, column='time', value=pd.date_range('{}-01-01'.format(str(year)), periods=m + n, freq='3H')[n:]) 

    # drop day, hour, forecast
    data_concat.drop(['hour', 'day', 'forecast'], axis=1, inplace=True)

    # save dataset(pickle)
    data_concat.to_pickle('/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_{}_AM_06.pkl'.format(year))

(736, 11)
(2920, 11)
(2920, 11)
(472, 11)

### 노트

- 2017년 예보 데이터의 하늘 상태(sky), 강수 형태(pre... form) 데이터가 부족하다.
- 2017년 하늘상태 데이터가 5월 ~ 12월 부분이 누락되어 있다.
- 2017년 강수형태 데이터는 거의 유사. 차후 확인 필요.

---

### data merge (2016, 2017, 2018)

In [11]:
# load dataset
file_forecast_2016 = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2016_AM_06.pkl'
file_forecast_2017 = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2017_AM_06.pkl'
file_forecast_2018 = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2018_AM_06.pkl'
file_forecast_2019 = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2019_AM_06.pkl'

data_forecast_2016 = pd.read_pickle(file_forecast_2016)
data_forecast_2017 = pd.read_pickle(file_forecast_2017)
data_forecast_2018 = pd.read_pickle(file_forecast_2018)
data_forecast_2019 = pd.read_pickle(file_forecast_2019)

data_forecast_2016.shape, data_forecast_2017.shape, data_forecast_2018.shape, data_forecast_2019.shape

((736, 9), (2920, 9), (2920, 9), (472, 9))

In [12]:
data_forecast_2016.tail()

,time,temperature_3H,sky,rainfall_probability,rainfall,snow,humidity,wind_speed,wind_direction
731,2016-12-31 21:00:00,-1.1,2.0,10.0,0.0,0.0,86.0,1.2,358.0
732,2017-01-01 00:00:00,0.6,2.0,10.0,0.0,0.0,82.0,0.5,178.0
733,2017-01-01 03:00:00,6.1,2.0,10.0,0.0,0.0,59.0,1.2,10.0
734,2017-01-01 06:00:00,8.1,2.0,10.0,0.0,0.0,60.0,1.6,260.0
735,2017-01-01 09:00:00,5.1,3.0,20.0,0.0,0.0,70.0,2.7,228.0

In [13]:
data_forecast_2017.tail()

,time,temperature_3H,sky,rainfall_probability,rainfall,snow,humidity,wind_speed,wind_direction
2915,2017-12-31 21:00:00,-2.0,1.0,0.0,0.0,0.0,70.0,3.6,330.0
2916,2018-01-01 00:00:00,0.0,1.0,0.0,0.0,0.0,65.0,3.5,344.0
2917,2018-01-01 03:00:00,2.0,1.0,0.0,0.0,0.0,50.0,1.7,353.0
2918,2018-01-01 06:00:00,2.0,1.0,0.0,0.0,0.0,40.0,1.6,338.0
2919,2018-01-01 09:00:00,-1.0,1.0,0.0,0.0,0.0,65.0,1.7,357.0

In [14]:
data_forecast_2018.head()

,time,temperature_3H,sky,rainfall_probability,rainfall,snow,humidity,wind_speed,wind_direction
0,2018-01-01 12:00:00,-1.0,1.0,0.0,0.0,0.0,75.0,2.7,270.0
1,2018-01-01 15:00:00,-1.0,1.0,0.0,0.0,0.0,80.0,4.0,270.0
2,2018-01-01 18:00:00,-1.0,1.0,0.0,0.0,0.0,90.0,4.2,313.0
3,2018-01-01 21:00:00,-2.0,1.0,0.0,0.0,0.0,75.0,4.0,343.0
4,2018-01-02 00:00:00,-2.0,1.0,0.0,0.0,0.0,70.0,3.2,34.0

In [15]:
data_forecast_2019.head()

,time,temperature_3H,sky,rainfall_probability,rainfall,snow,humidity,wind_speed,wind_direction
0,2019-01-01 12:00:00,-3.0,3.0,20.0,0.0,0.0,60.0,10.0,315.0
1,2019-01-01 15:00:00,-3.0,2.0,10.0,0.0,0.0,60.0,9.5,321.0
2,2019-01-01 18:00:00,-4.0,2.0,10.0,0.0,0.0,75.0,8.3,312.0
3,2019-01-01 21:00:00,-5.0,2.0,10.0,0.0,0.0,70.0,7.5,317.0
4,2019-01-02 00:00:00,-5.0,2.0,10.0,0.0,0.0,70.0,5.7,329.0

In [16]:
data_merge = pd.concat([data_forecast_2016, data_forecast_2017])
data_merge = pd.concat([data_merge, data_forecast_2018])
data_merge = pd.concat([data_merge, data_forecast_2019])
data_merge.reset_index(drop=True, inplace=True)
data_merge.tail()

,time,temperature_3H,sky,rainfall_probability,rainfall,snow,humidity,wind_speed,wind_direction
7043,2019-02-28 21:00:00,-1.0,1.0,0.0,0.0,0.0,100.0,3.4,296.0
7044,2019-03-01 00:00:00,3.0,1.0,0.0,0.0,0.0,90.0,2.5,288.0
7045,2019-03-01 03:00:00,8.0,1.0,0.0,0.0,0.0,60.0,1.9,302.0
7046,2019-03-01 06:00:00,10.0,1.0,0.0,0.0,0.0,45.0,4.1,288.0
7047,2019-03-01 09:00:00,7.0,1.0,0.0,0.0,0.0,65.0,4.0,273.0

In [17]:
data_merge.to_pickle('/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_final_03.pkl')

In [18]:
data_merge.shape

(7048, 9)

In [116]:
data_merge.iloc[:, 1:].describe()

,temperature_3H,sky,rainfall_probability,rainfall,snow,humidity,wind_speed,wind_direction
count,4616.000000,4616.000000,4616.00000,4616.000000,4616.000000,4616.000000,4616.000000,4616.000000
mean,9.924502,2.464255,18.17721,0.757366,0.021664,75.144064,3.751170,215.236135
std,9.940594,1.050419,18.56868,3.960757,0.293606,15.784952,2.465542,112.713392
min,-14.000000,1.000000,0.00000,0.000000,0.000000,25.000000,0.000000,0.000000
25%,2.000000,2.000000,10.00000,0.000000,0.000000,65.000000,2.000000,112.000000
50%,9.000000,2.000000,10.00000,0.000000,0.000000,75.000000,3.200000,240.000000
75%,17.000000,3.000000,20.00000,0.000000,0.000000,90.000000,5.000000,322.000000
max,35.000000,4.000000,91.00000,70.000000,5.000000,100.000000,23.900000,360.000000

---

### with snow, rainfall

In [31]:
# load dataset
file_forecast_2016 = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2016_AM_04.pkl'
file_forecast_2017 = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2017_AM_04.pkl'
file_forecast_2018 = '/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2018_AM_03.pkl'

data_forecast_2016 = pd.read_pickle(file_forecast_2016)
data_forecast_2017 = pd.read_pickle(file_forecast_2017)
data_forecast_2018 = pd.read_pickle(file_forecast_2018)

data_forecast_2016.shape, data_forecast_2017.shape, data_forecast_2018.shape

((376, 9), (959, 9), (1503, 9))

In [43]:
data_forecast_2016.head()

,time,temperature_3H,sky,rainfall_probability,humidity,wind_speed,wind_direction
0,2016-10-01 12:00:00,19.000000,4.0,30.0,90.0,0.8,12.0
1,2016-10-01 15:00:00,18.100000,4.0,30.0,95.0,1.1,140.0
2,2016-10-01 18:00:00,18.299999,4.0,30.0,94.0,0.7,120.0
3,2016-10-01 21:00:00,18.200001,4.0,80.0,95.0,1.1,94.0
4,2016-10-02 00:00:00,18.100000,4.0,90.0,95.0,0.6,14.0

In [44]:
data_forecast_2017.head()

,time,temperature_3H,sky,rainfall_probability,humidity,wind_speed,wind_direction
0,2017-01-01 12:00:00,4.1,3.0,20.0,77.0,0.5,176.0
1,2017-01-01 15:00:00,4.1,3.0,20.0,81.0,0.4,183.0
2,2017-01-01 18:00:00,4.4,4.0,30.0,81.0,0.9,213.0
3,2017-01-01 21:00:00,4.4,4.0,30.0,85.0,1.3,270.0
4,2017-01-02 00:00:00,6.4,4.0,60.0,86.0,1.3,302.0

In [45]:
data_forecast_2018.head()

,time,temperature_3H,sky,rainfall_probability,humidity,wind_speed,wind_direction
0,2018-01-01 12:00:00,-1.0,1.0,0.0,75.0,2.7,270.0
1,2018-01-01 15:00:00,-1.0,1.0,0.0,80.0,4.0,270.0
2,2018-01-01 18:00:00,-1.0,1.0,0.0,90.0,4.2,313.0
3,2018-01-01 21:00:00,-2.0,1.0,0.0,75.0,4.0,343.0
4,2018-01-02 00:00:00,-2.0,1.0,0.0,70.0,3.2,34.0

In [46]:
data_merge = pd.concat([data_forecast_2016, data_forecast_2017, data_forecast_2018])
data_merge.tail()

,time,temperature_3H,sky,rainfall_probability,humidity,wind_speed,wind_direction
2915,2018-12-31 21:00:00,-2.0,2.0,10.0,80.0,7.0,317.0
2916,2019-01-01 00:00:00,-2.0,3.0,20.0,75.0,7.7,311.0
2917,2019-01-01 03:00:00,-1.0,2.0,10.0,60.0,8.4,305.0
2918,2019-01-01 06:00:00,0.0,3.0,20.0,55.0,9.4,305.0
2919,2019-01-01 09:00:00,-3.0,2.0,10.0,65.0,9.9,304.0

In [47]:
data_merge.reset_index(drop=True, inplace=True)
data_merge.to_pickle('/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_whole_AM_01.pkl')

### 2016

In [66]:
# # reset index
# data_forecast_2016.reset_index(drop=True, inplace=True)

# # 실제 시기
# data_forecast_2016.insert(loc=0, column='time(46H later)', value=pd.date_range('2016-10-03', periods=736, freq='3H'))

# # 예보 시기
# data_forecast_2016.insert(loc=0, column='time(prediction)', value=pd.date_range('2016-10-01', periods=736, freq='3H') + timedelta(hours=2))

# # drop day, hour, forecast
# data_forecast_2016.drop(['day', 'hour', 'forecast'], axis=1, inplace=True)
# data_forecast_2016.tail()

### 2018

In [67]:
# reset index
data_forecast_2018.reset_index(drop=True, inplace=True)

# 실제 시기
n = 4
data_forecast_2018.insert(loc=0, column='time(predicted)', value=pd.date_range('2018-01-01', periods=2920 + n, freq='3H')[4:]) 

# 예보 시기
# data_forecast_2018.insert(loc=0, column='time(predictor)', value=pd.date_range('2018-01-01', periods=2920, freq='3H') + timedelta(hours=2))

# drop day, hour, forecast
data_forecast_2018.drop(['hour', 'day', 'forecast'], axis=1, inplace=True)
data_forecast_2018.tail()

,time(predicted),temperature_3H,sky,rainfall_probability,humidity,wind_speed,wind_direction,day,forecast
2915,2018-12-31 21:00:00,-2.0,2.0,10.0,80.0,7.0,317.0,31.0,13.0
2916,2019-01-01 00:00:00,-2.0,3.0,20.0,75.0,7.7,311.0,31.0,16.0
2917,2019-01-01 03:00:00,-1.0,2.0,10.0,60.0,8.4,305.0,31.0,19.0
2918,2019-01-01 06:00:00,0.0,3.0,20.0,55.0,9.4,305.0,31.0,22.0
2919,2019-01-01 09:00:00,-3.0,2.0,10.0,65.0,9.9,304.0,31.0,25.0

### 데이터 저장(csv, pickle)

In [68]:
# data_forecast_2016.to_pickle('/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2016_02.pkl')
data_forecast_2018.to_pickle('/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2018_04.pkl')

# data_forecast_2016.to_csv('/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2016_02.csv')
# data_forecast_2018.to_csv('/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2018_04.csv')

- 기온(3H), 하늘상태, 강수형태, 강수확률, 습도, 풍속, 풍향

---

In [69]:
data_raw = pd.read_pickle('/Users/quartz/GoogleDrive/ewp/forecast_dangjin/data_forecast_2016_02.pkl')
data_raw.tail()

,time(prediction),time(46H later),temperature_3H,sky,precipitation_form,rainfall_probability,humidity,wind_speed,wind_direction
731,2016-12-31 11:00:00,2017-01-02 09:00:00,5.5,2.0,0.0,10.0,69.0,1.9,312.0
732,2016-12-31 14:00:00,2017-01-02 12:00:00,3.3,1.0,0.0,0.0,72.0,3.2,314.0
733,2016-12-31 17:00:00,2017-01-02 15:00:00,1.1,1.0,0.0,0.0,77.0,3.2,322.0
734,2016-12-31 20:00:00,2017-01-02 18:00:00,-0.8,1.0,0.0,0.0,81.0,2.0,333.0
735,2016-12-31 23:00:00,2017-01-02 21:00:00,-1.5,1.0,0.0,0.0,82.0,2.2,337.0